In [41]:
import pandas as pd

customer_df = pd.read_csv(r"data/raw/Customer_Dataset.csv")
engagement_df = pd.read_csv(r"data/raw/ipl_engagement_dataset.csv")
social_df = pd.read_csv(r"data/raw/social_media_dataset.csv")
purchase_df = pd.read_csv(r"data/raw/purchase_dataset.csv")

In [42]:
# Merge datasets using customer_id
master_df = customer_df.merge(
    engagement_df,
    on="customer_id"
).merge(
    social_df,
    on="customer_id"
).merge(
    purchase_df,
    on="customer_id"
)

# Save merged dataset
master_df.to_csv(
    "data/processed/master_dataset.csv",
    index=False
)

print("Datasets merged successfully!")
master_df.head()

Datasets merged successfully!

,customer_id,age,gender,city,state,city_tier,occupation,monthly_income,cricket_interest_score,favorite_ipl_team,...,sports_equipment_spending_per_month_y,previous_cricket_gear_purchases,average_order_value,preferred_product_category,purchase_frequency_per_year,discount_sensitivity,cart_abandonment_rate,payment_method_preference,brand_loyalty_level,likely_to_buy_cricket_kit_y
0,CUST0001,21,Male,Mumbai,Maharashtra,Tier 1,Student,18000,8.7,Mumbai Indians,...,3200,5,4100,Bats,4,Medium,0.24,UPI,Medium,Yes
1,CUST0002,34,Female,Bengaluru,Karnataka,Tier 1,Working Professional,72000,6.2,Royal Challengers Bengaluru,...,1800,2,2200,Jerseys,2,High,0.48,Debit Card,Low,No
2,CUST0003,18,Male,Hyderabad,Telangana,Tier 1,Student,12000,9.1,Sunrisers Hyderabad,...,5400,8,7200,Full Kits,6,Low,0.12,Credit Card,High,Yes
3,CUST0004,42,Male,Jaipur,Rajasthan,Tier 2,Business,98000,5.4,Rajasthan Royals,...,900,1,1100,Accessories,1,Medium,0.29,Cash on Delivery,Low,No
4,CUST0005,27,Female,Pune,Maharashtra,Tier 1,Working Professional,56000,7.5,Chennai Super Kings,...,4100,6,5300,Shoes,5,Medium,0.21,UPI,Medium,Yes

In [43]:
print(master_df.shape)

(3500, 58)

In [44]:
master_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 58 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   customer_id                             3500 non-null   object
 1   age                                     3500 non-null   int64
 2   gender                                  3500 non-null   object
 3   city                                    3500 non-null   object
 4   state                                   3500 non-null   object
 5   city_tier                               3500 non-null   object
 6   occupation                              3500 non-null   object
 7   monthly_income                          3500 non-null   int64
 8   cricket_interest_score                  3487 non-null   float64
 9   favorite_ipl_team                       3500 non-null   object
 10  favorite_player                         3487 non-null   object
 11  Unnamed: 11                             3500 non-null   int64
 12  preferred_streaming_platform            3500 non-null   object
 13  fantasy_cricket_user                    3500 non-null   object
 14  sports_equipment_spending_per_month_x   3500 non-null   int64
 15  preferred_shopping_platform_x           3500 non-null   object
 16  cricket_search_frequency_per_month      3500 non-null   int64
 17  device_type                             3500 non-null   object
 18  digital_engagement_score                3472 non-null   float64
 19  likely_to_buy_cricket_kit_x             3500 non-null   object
 20  engagement_id                           3500 non-null   object
 21  favorite_match_type                     3500 non-null   object
 22  average_match_watch_time_minutes        3500 non-null   int64
 23  matches_watched_per_season              3500 non-null   int64
 24  preferred_ad_format                     3500 non-null   object
 25  ad_click_rate                           3500 non-null   float64
 26  sports_content_watch_hours_per_week     3500 non-null   float64
 27  engagement_during_csk_matches           3500 non-null   int64
 28  engagement_during_rcb_matches           3500 non-null   int64
 29  engagement_during_mi_matches            3500 non-null   int64
 30  streaming_device_preference             3500 non-null   object
 31  second_screen_usage                     3500 non-null   object
 32  social_media_activity_during_matches    3500 non-null   object
 33  engagement_potential_score              3500 non-null   float64
 34  social_id                               3500 non-null   object
 35  preferred_social_media_platform         3500 non-null   object
 36  cricket_reels_watched_per_week          3500 non-null   int64
 37  sports_content_likes_per_week           3500 non-null   int64
 38  sports_content_shares_per_week          3500 non-null   int64
 39  favorite_cricket_content_type           3500 non-null   object
 40  influencer_engagement_level             3500 non-null   object
 41  fantasy_cricket_content_interaction     3500 non-null   object
 42  average_daily_social_media_usage_hours  3500 non-null   float64
 43  preferred_content_format                3500 non-null   object
 44  sports_brand_follow_count               3500 non-null   int64
 45  social_media_ad_click_rate              3500 non-null   float64
 46  purchase_id                             3500 non-null   object
 47  preferred_shopping_platform_y           3500 non-null   object
 48  sports_equipment_spending_per_month_y   3500 non-null   int64
 49  previous_cricket_gear_purchases         3500 non-null   int64
 50  average_order_value                     3500 non-null   int64
 51  preferred_product_category              3500 non-null   object
 52  purchase_frequency_per_year             3500 non-null   int64
 53  discount_sensitivity                    3500 non-null   object
 54  cart_abandonment_rate                   3500 non-null   float64
 55  payment_method_preference               3500 non-null   object
 56  brand_loyalty_level                     3500 non-null   object
 57  likely_to_buy_cricket_kit_y             3500 non-null   object
dtypes: float64(8), int64(18), object(32)
memory usage: 1.5+ MB

In [45]:
drop_columns = [
    "state",
    "city_tier",
    "cricket_interest_score",
    "favorite_player",
    "engagement_id",
    "social_id",
    "purchase_id",
    "Unnamed: 11",

    "sports_equipment_spending_per_month_y",
    "preferred_shopping_platform_y",
    "likely_to_buy_cricket_kit_x"
]
master_df.drop(columns=drop_columns, inplace=True)

In [46]:
master_df.rename(columns={
    "sports_equipment_spending_per_month_x":
        "sports_equipment_spending_per_month",

    "preferred_shopping_platform_x":
        "preferred_shopping_platform",

    "likely_to_buy_cricket_kit_y":
        "likely_to_buy_cricket_kit"
}, inplace=True)

In [47]:
master_df.isna().sum()

customer_id                                0
age                                        0
gender                                     0
city                                       0
occupation                                 0
monthly_income                             0
favorite_ipl_team                          0
preferred_streaming_platform               0
fantasy_cricket_user                       0
sports_equipment_spending_per_month        0
preferred_shopping_platform                0
cricket_search_frequency_per_month         0
device_type                                0
digital_engagement_score                  28
favorite_match_type                        0
average_match_watch_time_minutes           0
matches_watched_per_season                 0
preferred_ad_format                        0
ad_click_rate                              0
sports_content_watch_hours_per_week        0
engagement_during_csk_matches              0
engagement_during_rcb_matches              0
engagement_during_mi_matches               0
streaming_device_preference                0
second_screen_usage                        0
social_media_activity_during_matches       0
engagement_potential_score                 0
preferred_social_media_platform            0
cricket_reels_watched_per_week             0
sports_content_likes_per_week              0
sports_content_shares_per_week             0
favorite_cricket_content_type              0
influencer_engagement_level                0
fantasy_cricket_content_interaction        0
average_daily_social_media_usage_hours     0
preferred_content_format                   0
sports_brand_follow_count                  0
social_media_ad_click_rate                 0
previous_cricket_gear_purchases            0
average_order_value                        0
preferred_product_category                 0
purchase_frequency_per_year                0
discount_sensitivity                       0
cart_abandonment_rate                      0
payment_method_preference                  0
brand_loyalty_level                        0
likely_to_buy_cricket_kit                  0
dtype: int64

In [48]:
master_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 47 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   customer_id                             3500 non-null   object
 1   age                                     3500 non-null   int64
 2   gender                                  3500 non-null   object
 3   city                                    3500 non-null   object
 4   occupation                              3500 non-null   object
 5   monthly_income                          3500 non-null   int64
 6   favorite_ipl_team                       3500 non-null   object
 7   preferred_streaming_platform            3500 non-null   object
 8   fantasy_cricket_user                    3500 non-null   object
 9   sports_equipment_spending_per_month     3500 non-null   int64
 10  preferred_shopping_platform             3500 non-null   object
 11  cricket_search_frequency_per_month      3500 non-null   int64
 12  device_type                             3500 non-null   object
 13  digital_engagement_score                3472 non-null   float64
 14  favorite_match_type                     3500 non-null   object
 15  average_match_watch_time_minutes        3500 non-null   int64
 16  matches_watched_per_season              3500 non-null   int64
 17  preferred_ad_format                     3500 non-null   object
 18  ad_click_rate                           3500 non-null   float64
 19  sports_content_watch_hours_per_week     3500 non-null   float64
 20  engagement_during_csk_matches           3500 non-null   int64
 21  engagement_during_rcb_matches           3500 non-null   int64
 22  engagement_during_mi_matches            3500 non-null   int64
 23  streaming_device_preference             3500 non-null   object
 24  second_screen_usage                     3500 non-null   object
 25  social_media_activity_during_matches    3500 non-null   object
 26  engagement_potential_score              3500 non-null   float64
 27  preferred_social_media_platform         3500 non-null   object
 28  cricket_reels_watched_per_week          3500 non-null   int64
 29  sports_content_likes_per_week           3500 non-null   int64
 30  sports_content_shares_per_week          3500 non-null   int64
 31  favorite_cricket_content_type           3500 non-null   object
 32  influencer_engagement_level             3500 non-null   object
 33  fantasy_cricket_content_interaction     3500 non-null   object
 34  average_daily_social_media_usage_hours  3500 non-null   float64
 35  preferred_content_format                3500 non-null   object
 36  sports_brand_follow_count               3500 non-null   int64
 37  social_media_ad_click_rate              3500 non-null   float64
 38  previous_cricket_gear_purchases         3500 non-null   int64
 39  average_order_value                     3500 non-null   int64
 40  preferred_product_category              3500 non-null   object
 41  purchase_frequency_per_year             3500 non-null   int64
 42  discount_sensitivity                    3500 non-null   object
 43  cart_abandonment_rate                   3500 non-null   float64
 44  payment_method_preference               3500 non-null   object
 45  brand_loyalty_level                     3500 non-null   object
 46  likely_to_buy_cricket_kit               3500 non-null   object
dtypes: float64(7), int64(16), object(24)
memory usage: 1.3+ MB

In [49]:
input_features = [

    # SECTION 1 — BASIC PROFILE
    "age",
    "gender",
    "city",
    "occupation",
    "monthly_income",

    # SECTION 2 — IPL INTEREST
    "favorite_ipl_team",
    "matches_watched_per_season",
    "fantasy_cricket_user",

    # SECTION 3 — DIGITAL ENGAGEMENT
    "preferred_social_media_platform",
    "sports_content_watch_hours_per_week",
    "preferred_content_format",
    "social_media_activity_during_matches",

    # SECTION 4 — SHOPPING BEHAVIOR
    "sports_equipment_spending_per_month",
    "preferred_shopping_platform"
]
target = "likely_to_buy_cricket_kit"

In [50]:
final_columns = input_features + [target]

model_df = master_df[final_columns]

In [51]:
model_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 15 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   age                                   3500 non-null   int64
 1   gender                                3500 non-null   object
 2   city                                  3500 non-null   object
 3   occupation                            3500 non-null   object
 4   monthly_income                        3500 non-null   int64
 5   favorite_ipl_team                     3500 non-null   object
 6   matches_watched_per_season            3500 non-null   int64
 7   fantasy_cricket_user                  3500 non-null   object
 8   preferred_social_media_platform       3500 non-null   object
 9   sports_content_watch_hours_per_week   3500 non-null   float64
 10  preferred_content_format              3500 non-null   object
 11  social_media_activity_during_matches  3500 non-null   object
 12  sports_equipment_spending_per_month   3500 non-null   int64
 13  preferred_shopping_platform           3500 non-null   object
 14  likely_to_buy_cricket_kit             3500 non-null   object
dtypes: float64(1), int64(4), object(10)
memory usage: 410.3+ KB

In [55]:
model_df.city.unique().size

71

In [ ]:
mappings = {

    "gender": {
        "Male": 0,
        "Female": 1
    },

    "fantasy_cricket_user": {
        "No": 0,
        "Yes": 1
    },

    "preferred_social_media_platform": {
        "Instagram": 0,
        "YouTube": 1,
        "Twitter": 2,
        "Facebook": 3
    }
}

In [52]:
Labels=['gender', 'city', 'occupation', 'favorite_ipl_team', 'fantasy_cricket_user',
        'preferred_social_media_platform', 'preferred_content_format','social_media_activity_during_matches','preferred_shopping_platform','likely_to_buy_cricket_kit']

In [31]:
from sklearn.preprocessing import LabelEncoder
for col in Labels:
    Le =LabelEncoder()
    model_df[col]=Le.fit_transform(model_df[col])

C:\Users\nethi\AppData\Local\Temp\ipykernel_9112\3782317602.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  model_df[col]=Le.fit_transform(model_df[col])
C:\Users\nethi\AppData\Local\Temp\ipykernel_9112\3782317602.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  model_df[col]=Le.fit_transform(model_df[col])
C:\Users\nethi\AppData\Local\Temp\ipykernel_9112\3782317602.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  model_df[col]=Le.fit_transform(model_df[col])
C:\Users\nethi\AppData\Local\Temp\ipykernel_9112\3782317602.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  model_df[col]=Le.fit_transform(model_df[col])
C:\Users\nethi\AppData\Local\Temp\ipykernel_9112\3782317602.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  model_df[col]=Le.fit_transform(model_df[col])
C:\Users\nethi\AppData\Local\Temp\ipykernel_9112\3782317602.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  model_df[col]=Le.fit_transform(model_df[col])
C:\Users\nethi\AppData\Local\Temp\ipykernel_9112\3782317602.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  model_df[col]=Le.fit_transform(model_df[col])
C:\Users\nethi\AppData\Local\Temp\ipykernel_9112\3782317602.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  model_df[col]=Le.fit_transform(model_df[col])
C:\Users\nethi\AppData\Local\Temp\ipykernel_9112\3782317602.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  model_df[col]=Le.fit_transform(model_df[col])
C:\Users\nethi\AppData\Local\Temp\ipykernel_9112\3782317602.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  model_df[col]=Le.fit_transform(model_df[col])

In [33]:
model_df.head()

,age,gender,city,occupation,monthly_income,favorite_ipl_team,matches_watched_per_season,fantasy_cricket_user,preferred_social_media_platform,sports_content_watch_hours_per_week,preferred_content_format,social_media_activity_during_matches,sports_equipment_spending_per_month,preferred_shopping_platform,likely_to_buy_cricket_kit
0,21,1,40,3,18000,5,61,1,1,18.5,3,0,2400,0,1
1,34,0,8,4,72000,8,39,0,3,8.2,2,2,1200,2,0
2,18,1,24,3,12000,9,72,1,1,21.4,3,0,3100,0,1
3,42,1,27,1,98000,7,26,0,0,4.3,1,1,1800,3,0
4,27,0,51,4,56000,0,76,1,1,24.1,3,0,2200,0,1

In [34]:
X = model_df.drop(
    "likely_to_buy_cricket_kit",
    axis=1
)
Y=model_df["likely_to_buy_cricket_kit"]

In [36]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

In [37]:
import pickle

pickle.dump(
    scaler,
    open("models/scaler.pkl", "wb")
)

In [40]:
model_df.head()

,age,gender,city,occupation,monthly_income,favorite_ipl_team,matches_watched_per_season,fantasy_cricket_user,preferred_social_media_platform,sports_content_watch_hours_per_week,preferred_content_format,social_media_activity_during_matches,sports_equipment_spending_per_month,preferred_shopping_platform,likely_to_buy_cricket_kit
0,21,1,40,3,18000,5,61,1,1,18.5,3,0,2400,0,1
1,34,0,8,4,72000,8,39,0,3,8.2,2,2,1200,2,0
2,18,1,24,3,12000,9,72,1,1,21.4,3,0,3100,0,1
3,42,1,27,1,98000,7,26,0,0,4.3,1,1,1800,3,0
4,27,0,51,4,56000,0,76,1,1,24.1,3,0,2200,0,1

In [39]:
df = pd.read_csv(
    r"data/processed/feature_engineered_dataset.csv"
)

FileNotFoundError: [Errno 2] No such file or directory: 'data/processed/feature_engineered_dataset.csv'

In [ ]:
cluster_features = [

    "age",
    "monthly_income",
    "matches_watched_per_season",
    "sports_content_watch_hours_per_week",
    "sports_equipment_spending_per_month",

    "overall_engagement_score",
    "purchase_intent_score",
    "social_influence_score",
    "hardcore_fan_score"
]

In [56]:
df = pd.read_csv(
    "data/processed/processed_dataset.csv"
)

In [57]:
cluster_features = [

    "age",
    "monthly_income",
    "matches_watched_per_season",
    "sports_content_watch_hours_per_week",
    "sports_equipment_spending_per_month"
]
X = df[cluster_features]

In [58]:

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
kmeans = KMeans(
    n_clusters=4,
    random_state=42,
    n_init=10
)

df["cluster"] = kmeans.fit_predict(X)

In [59]:
score = silhouette_score(
    X,
    df["cluster"]
)

print(f"\nSilhouette Score: {score:.3f}")

Silhouette Score: 0.383